name: CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: docker:latest
    services:
      docker-dind:
        image: docker:dind
    steps:
      - uses: actions/checkout@v2
      - name: Run Sanity check
        run: |
          echo polica!
          docker version
      - shell: bash
        run: make build
  push:
    runs-on: ubuntu-latest
    container: docker:latest
    services:
      docker-dind:
        image: docker:dind
    steps:
      - uses: actions/checkout@v2
      - name: push to registry
        env: # Ou como uma variável de ambiente
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: make push
  deploy:
    runs-on: ubuntu-latest
    container: kaykelins/nomad:cli
    
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        env: 
          POLICA_BOT_TOKEN: ${{ secrets.POLICA_BOT_TOKEN }}
          NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
          NOMAD_ADDR: ${{ secrets.NOMAD_ADDR }}
        run: make deploy