name: CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: docker
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/action-setup-waypoint
        with:
          version: '0.1.3'
      - name: Run Sanity check
        run: echo polica!