name: CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: docker:latest
    services:
      docker-dind:
        image: docker:dind
    steps:
      - uses: actions/checkout@v2
      - name: Run Sanity check
        run: |
          echo polica!
          docker version
      - name: buid
        run: docker build -f dev.Dockerfile -t kaykelins/polica-bot:$GITHUB_SHA .
  push:
    runs-on: ubuntu-latest
    container: docker:latest
    services:
      docker-dind:
        image: docker:dind
    steps:
      - uses: actions/checkout@v2
      - name: push to registry
        env: # Ou como uma variável de ambiente
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run:
          echo $DOCKER_TOKEN | docker login -u kaykelins --password-stdin
          docker push kaykelins/polica-bot:$GITHUB_SHA
  deploy:
    runs-on: ubuntu-latest
    container: kaykelins/nomad:cli
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        env: 
          POLICA_BOT_TOKEN: ${{ secrets.POLICA_BOT_TOKEN }}
          NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
          NOMAD_ADDR: ${{ secrets.NOMAD_ADDR }}
        run: |
          echo $NOMAD_ADDR
          sed -i 's|<POLICA_BOT_TOKEN>|'$POLICA_BOT_TOKEN'|g' job/bot.nomad
          sed -i 's|<GIT_COMMIT>|'$GITHUB_SHA'|g' job/bot.nomad
          nomad job run job/bot.nomad