name: CI
on:
  push:
    branches: [ devops ]
  pull_request:
    branches: [ devops ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: docker:latest
    services:
      docker-dind:
        image: docker:dind
    steps:
      - uses: actions/checkout@v2
      - run: |
          wget -q -O /tmp/waypoint.zip https://releases.hashicorp.com/waypoint/0.1.3/waypoint_0.1.3_linux_amd64.zip
          unzip -d /usr/local/bin /tmp/waypoint.zip
          rm -rf /tmp/waypoint*
      - run:
          echo $SECRET_JSON > secret.json
        env: 
          SECRET_JSON: ${{ secrets.SECRET_JSON }}
      - run:
          waypoint init
      - run:
          waypoint build
      - uses: actions/upload-artifact@v2
        with:
          name: waypoint_data
          path: data.db
      - uses: actions/upload-artifact@v2
        with:
          name: waypoint_folder
          path: .waypoint
  deploy:
    runs-on: ubuntu-latest
    container: docker:latest
    services:
      docker-dind:
        image: docker:dind
    steps:
      - uses: actions/checkout@v2
      - run: |
          wget -q -O /tmp/waypoint.zip https://releases.hashicorp.com/waypoint/0.1.3/waypoint_0.1.3_linux_amd64.zip
          unzip -d /usr/local/bin /tmp/waypoint.zip
          rm -rf /tmp/waypoint*
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: waypoint_data
      - run:
          echo $SECRET_JSON > secret.json
        env: 
          SECRET_JSON: ${{ secrets.SECRET_JSON }}
      - run:
          waypoint init
      - run:
          waypoint deploy