name: CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: docker:latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Sanity check
        run: echo polica!
      - name: Docker version
        run: docker version