name: CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: docker:latest
    services:
      docker-dind:
        image: docker:dind
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/action-setup-waypoint
      - run: waypoint init