name: CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: docker:latest
    services:
      docker-dind:
        image: docker:dind
    steps:
      - uses: actions/checkout@v2
      - run: |
          wget -q -O /tmp/waypoint.zip https://releases.hashicorp.com/waypoint/0.1.3/waypoint_0.1.3_linux_amd64.zip
          sudo unzip -d /usr/local/bin /tmp/waypoint.zip
          rm -rf /tmp/waypoint*
      - run:
          waypoint init